---
on:
  push:
  workflow_dispatch:
    inputs:
      push:
        default: true
        type: boolean
        required: false
permissions:
    actions: none
    attestations: none
    checks: none
    contents: none
    deployments: none
    discussions: none
    id-token: none
    issues: none
    models: none
    packages: none
    pages: none
    pull-requests: none
    repository-projects: none
    security-events: none
    statuses: none
jobs:
  debug:
    permissions: 
      actions: none
      attestations: none
      checks: none
      contents: none
      deployments: none
      discussions: none
      id-token: none
      issues: none
      models: none
      packages: none
      pages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::group::GITHUB object"
          echo "${{ toJson(github) }}"
          echo "::endgroup::"
          echo "::group::INPUTS object"
          echo "${{ toJson(inputs) }}"
          echo "::endgroup::"
          
      - if: github.event_name == 'push'
        name: Inputs PUSH
        run: |
          echo "This is the 'inputs' value '${{ fromJson(inputs) }}'"
          echo " TRUE ${{ toJson(inputs) == {}             && '' }}"

      - if: github.event_name == 'workflow_dispatch'
        name: Inputs WORKFLOW_DISPATCH
        run: |
          echo "This is the 'inputs' value '${{ fromJson(inputs) }}'"
          echo " TRUE ${{ fromJson(inputs.push) == 'true'  && ''           }}"
          echo "FALSE ${{ fromJson(inputs.push) == 'false' && '--dry-run'  }}"

      # - id: clear-space
      #   uses: awslabs/mcp/.github/actions/clear-space-ubuntu-latest-agressively@main
      # - name: Step to demonstrate how to access outputs (no need for this)
      #   id: echo-output
      #   run: |
      #     echo "before: ${BEFORE}"
      #     echo "after: ${AFTER}"
      #   env:
      #     BEFORE: ${{ steps.clear-space.outputs.before}}
      #     AFTER: ${{ steps.clear-space.outputs.after}}
