---
on:
  push:
  workflow_dispatch:
    inputs:
      push:
        default: true
        type: boolean
        required: false
permissions:
    actions: none
    attestations: none
    checks: none
    contents: none
    deployments: none
    discussions: none
    id-token: none
    issues: none
    models: none
    packages: none
    pages: none
    pull-requests: none
    repository-projects: none
    security-events: none
    statuses: none
jobs:
  debug:
    permissions: 
      actions: none
      attestations: none
      checks: none
      contents: none
      deployments: none
      discussions: none
      id-token: none
      issues: none
      models: none
      packages: none
      pages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::group::GITHUB object"
          echo "${{ toJson(github) }}"
          echo "::endgroup::"
          echo "::group::INPUTS object"
          echo "${{ toJson(inputs) }}"
          echo "::endgroup::"

      - name: Inputs
        run: |
          echo "${{ github.event_name == 'push' && inputs && '' || ( github.event_name == 'workflow_dispatch' && inputs && fromJson(inputs.push) == false && '--dry-run' || '' ) }}"

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Checker
        id: gamer
        uses: scottschreckengaust/mcp/.github/actions/build-and-push-container-image@main
        with:
          image: scott-mcp-server
          version: 0.0.0
          public-erc-role-to-assume: 'arn:aws:iam:123456789012:role/AssumeRoleForPublicECR'
          public-erc-registry-alias: 'a1c4e6g8'
          public-erc-aws-region: 'us-east-1'
          push: false

      # - id: clear-space
      #   uses: awslabs/mcp/.github/actions/clear-space-ubuntu-latest-agressively@main
      # - name: Step to demonstrate how to access outputs (no need for this)
      #   id: echo-output
      #   run: |
      #     echo "before: ${BEFORE}"
      #     echo "after: ${AFTER}"
      #   env:
      #     BEFORE: ${{ steps.clear-space.outputs.before}}
      #     AFTER: ${{ steps.clear-space.outputs.after}}
