---
name: Gate
run-name: ${{ github.workflow}} by @${{ github.triggering_actor }} for @${{ github.actor }}
description: A build has all checks cleared

on:
  status:
  workflow_run:
    branches: 
      - 'main'
    types: 
      - completed
    workflows: ['Gate']
permissions:
  actions: none
  attestations: none
  checks: none
  contents: none
  deployments: none
  discussions: none
  id-token: none
  issues: none
  models: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  commit-status-success:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.event_name}}-${{ github.ref}}
    if: >-
      github.event_name == 'status' &&
      github.event.state == 'success'
    runs-on: ubuntu-latest
    # error, failure, pending, or success
    steps:
      - env:
          DESCRIPTION: ${{ github.event.description }}
        run: |
          echo The status is error or failed: $DESCRIPTION
  workflow-run-completed-on-success:
    if: >-
      github.event_name == 'workflow_run' &&
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo 'The triggering workflow passed'
          echo "::group::EVENT object"
          echo "${{ toJson(github.event) }}"
          echo "::endgroup::"
