on:
  workflow_dispatch:
permissions:
    actions: none
    attestations: none
    checks: none
    contents: none
    deployments: none
    discussions: none
    id-token: none
    issues: none
    models: none
    packages: none
    pages: none
    pull-requests: none
    repository-projects: none
    security-events: none
    statuses: none
jobs:
  beta:
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      checks: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      ## TODO: verify only on main, and requestor from maintainers or admin (not from the away team)
      - run: |
          echo "Check prior runs"
          echo "::group::GITHUB object"
          echo "${{ toJson(github) }}"
          echo "::endgroup::" 
          echo "::group::check-runs object"
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/commits/${{ github.sha }}/check-runs | jq
          echo "::endgroup::" 

          ## exclude this workflow's check-suite
          echo "::group::check-suite object"
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/commits/${{ github.sha }}/check-suites | jq
          echo "::endgroup::" 

          ## set a statuses state if "success" and exit failure otherwise
          #echo "::group::statuses object"
          #gh api \
          #  --method POST \
          #  -H "Accept: application/vnd.github+json" \
          #  -H "X-GitHub-Api-Version: 2022-11-28" \
          #  /repos/${{ github.repository }}/statuses/${{ github.sha }} \
          #  -f "state=success" \
          #  -f "context=${{ github.workflow }}"
          #  -f "target_url=https://example.com/build/status" \
          #  -f "description=forced success" \
          #echo "::endgroup::" 

