---
name: Simpleton
on:
  workflow_dispatch:
permissions:
    actions: none
    attestations: none
    checks: read
    contents: none
    deployments: none
    discussions: none
    id-token: none
    issues: none
    models: none
    packages: none
    pages: none
    pull-requests: none
    repository-projects: none
    security-events: none
    statuses: read
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::group::GITHUB object"
          echo "${{ toJson(github) }}"
          echo "::endgroup::"

  simple:
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      checks: read
      statuses: read
    name: Simple
    runs-on: ubuntu-latest
    steps:
      - name: Simpler
        run: |
          echo "simplest"
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/scottschreckengaust/monorepo-release/commits/main/status | jq
