---
name: Status
run-name: ${{ github.workflow}} by @${{ github.triggering_actor }} for @${{ github.actor }}
description: A build has all checks cleared

on:
  status:
permissions:
  actions: none
  attestations: none
  checks: none
  contents: none
  deployments: none
  discussions: none
  id-token: none
  issues: none
  models: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  commit-status-success:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.event_name}}-${{ github.ref}}
    if: >-
      github.event_name == 'status' &&
      github.event.state == 'success'
    runs-on: ubuntu-latest
    # error, failure, pending, or success
    steps:
      - env:
          DESCRIPTION: ${{ github.event.description }}
        run: |
          echo The status is error or failed: $DESCRIPTION
