on:
  status:
  check_run:
     types:
       - created
       - rerequested
       - completed
       - requested_action
  check_suite: 
    types:
      - completed
permissions: write-all
jobs:
  hereiam:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::group::GITHUB object"
          echo "${{ toJson(github) }}"
          echo "::endgroup::"
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/scottschreckengaust/monorepo-release/commits/${{ github.ref }}/check-runs | jq
