on:
  status:
  check_run:
     types:
       - completed
permissions: write-all
jobs:
  hereiam:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::group::GITHUB object"
          echo "${{ toJson(github) }}"
          echo "::endgroup::"    
