on:
  status:
  check_run:
     types:
       - completed
permissions:
  statuses: write
  checks: write
jobs:
  hereiam:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::group::GITHUB object"
          echo "${{ toJson(github) }}"
          echo "::endgroup::"    
